general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock; powerprofilesctl set power-saver
    after_sleep = hyprctl dispatch dpms on; powerprofilesctl set balanced
  }

listener {
    timeout = 120
    on-timeout = brightnessctl set 20%
    on-resume = brightnessctl set 100%
  }



listener {
    timeout = 300
    on-timeout = hyprlock
  }

  listener {
      timeout = 600
      on-timeout = systemctl suspend
    }
