monitor=,preferred,auto,2

env = XDG_CURRENT_DESKTOP,Hyprland

# Keybindings
bind = SUPER, T, exec, ghostty

bind = SUPER, Q, killactive

bind = super, M, exit

# Screen Brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

# Windows
bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

bind = SUPER, SPACE, exec, rofi -show drun

bind = SUPER, E, exec, ghostty -e yazi

bind = SUPER SHIFT, H, swapwindow, l
bind = SUPER SHIFT, J, swapwindow, d
bind = SUPER SHIFT, K, swapwindow, u
bind = SUPER SHIFT, L, swapwindow, r
bind = SUPER, code:10, workspace, 1
bind = SUPER, code:11, workspace, 2
bind = SUPER, code:12, workspace, 3
bind = SUPER, code:13, workspace, 4
bind = SUPER SHIFT, code:10, movetoworkspace, 1
bind = SUPER SHIFT, code:11, movetoworkspace, 2
bind = SUPER SHIFT, code:12, movetoworkspace, 3
bind = SUPER SHIFT, code:13, movetoworkspace, 4

bind = CTRL ALT, L, exec, hyprlock

bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

exec-once = ghostty

exec-once = uwsm app -- hyprpaper

exec-once = uwsm app -- hyprpolkitagent

# Styling
decoration {
    rounding = 5
  }

general {
    gaps_in = 6
    gaps_out = 12
  }

animations {
    enabled = false # Turned off until I can style. They are too slow by default.
  }
